name: pytorch1.12
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py37h5e8e339_1
  - async-timeout=3.0.1=py_1000
  - attrs=24.2.0=pyh71513ae_0
  - blinker=1.6.3=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py37hd23a5d3_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cachetools=5.5.0=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - chardet=4.0.0=py37h89c1867_3
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.3=py37h89c1867_0
  - cryptography=38.0.2=py37h5994e8b_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - einops=0.3.0=py_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=h267a509_2
  - google-auth=2.23.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpc-cpp=1.48.1=h30feacc_0
  - grpcio=1.48.1=py37hd557365_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.4=py37h7cecad7_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=20_linux64_openblas
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=20_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.44=hadc24fc_0
  - libprotobuf=3.21.8=h6239696_0
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.4.0=h82bc61c_5
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.3.1=hb9d3cd8_2
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib-base=3.5.3=py37hf395dca_2
  - multidict=6.0.2=py37h540881e_1
  - munkres=1.0.7=py_1
  - ncurses=6.5=he02047a_1
  - networkx=2.7=pyhd8ed1ab_0
  - numpy=1.21.6=py37h976b520_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=h7d73246_1
  - openpyxl=3.0.10=py37h540881e_1
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.3.5=py37he8f5f7f_0
  - pip=24.0=pyhd8ed1ab_0
  - protobuf=4.21.8=py37hd23a5d3_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyasn1=0.5.1=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.7=4_cp37m
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py37hf9e9bfc_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - setuptools=59.8.0=py37h89c1867_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.46.1=h9eae976_0
  - tensorboard=2.11.2=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py37h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h540881e_1
  - werkzeug=2.2.3=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.2.6=h166bdaf_0
  - yarl=1.7.2=py37h540881e_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aistudio-sdk==0.2.6
      - annotated-types==0.5.0
      - anyio==3.7.1
      - babel==2.14.0
      - bce-python-sdk==0.9.23
      - colorama==0.4.6
      - colorlog==6.9.0
      - datasets==2.13.2
      - dill==0.3.4
      - exceptiongroup==1.2.2
      - fastapi==0.103.2
      - filelock==3.12.2
      - flask==2.2.5
      - flask-babel==3.1.0
      - fsspec==2023.1.0
      - future==1.0.0
      - h11==0.14.0
      - huggingface-hub==0.16.4
      - itsdangerous==2.1.2
      - jieba==0.42.1
      - jinja2==3.1.4
      - kenlm==0.2.0
      - loguru==0.7.2
      - markdown-it-py==2.2.0
      - mdurl==0.1.2
      - multiprocess==0.70.12.2
      - onnx==1.14.1
      - paddle2onnx==1.1.0
      - paddlefsl==1.1.0
      - paddlenlp==2.7.2
      - pillow==9.5.0
      - prettytable==3.7.0
      - psutil==6.1.0
      - pyahocorasick==2.0.0
      - pyarrow==12.0.1
      - pybind11==2.13.6
      - pycorrector==1.1.0
      - pycryptodome==3.21.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.17.2
      - pypinyin==0.53.0
      - pyyaml==6.0.1
      - rarfile==4.2
      - regex==2024.4.16
      - requests==2.31.0
      - rich==13.8.1
      - safetensors==0.4.5
      - sentencepiece==0.2.0
      - seqeval==1.2.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.27.0
      - tokenizers==0.13.3
      - tool-helpers==0.1.2
      - torch==1.12.1+cu116
      - torchaudio==0.12.1+cu116
      - torchvision==0.13.1+cu116
      - tqdm==4.67.1
      - transformers==4.30.2
      - typer==0.15.1
      - urllib3==2.0.7
      - uvicorn==0.22.0
      - visualdl==2.5.3
      - wcwidth==0.2.13
      - xxhash==3.5.0
prefix: /home/n40/anaconda3/envs/pytorch1.12
